management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
  security:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://auth.artemovskiy.me/realms/coliving-erp
springdoc:
  api-docs:
    path: /api-docs
web:
  baseUrl: http://localhost:3000
oidc:
  clientID: test
logging:
  level:
    org:
      springframework:
        security: TRACE
